### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by egiovanoudi** [brennanaba/ABlooper#12]
Hi,
I get this error for some of the PDBs, e.g. for 1dlf:

![Χωρίς τίτλο](https://user-images.githubusercontent.com/74119262/202442852-ec53d460-6637-4e32-b147-1a421a68c3c2.png)

**Comment by brennanaba** [comment]
Hi @elyooo 

It is a bit hard to know exactly what is going on from that error. My guess is that this is due to some letter being inserted at the sixteenth position in some of the atom entries of your PDB file. This would mess up the ABlooper PDB parsing script. I have pasted a few example PDB lines that would mess up the parsing script to show you what I mean:

ATOM     17  N  AGLN H   3      30.338   7.011   1.308  0.50 16.97           N
ATOM     18  CA AGLN H   3      31.007   7.863   2.296  0.50 17.06           C
ATOM     19  C  AGLN H   3      30.779   9.318   1.917  0.50 16.59           C 


If removing these letters does not fix it, then please feel free to send the PDB file that breaks it. 

All the best,

Brennan
